# Browser settings
NAME = "EchoG"
VERSION = "1.0.2"
PROTOCOL = "echog"
HOME_PAGE = "search.echog"
DEFAULT_FONT = "Arial"

# Theme colors
BACKGROUND_PRIMARY = "#181818"
BACKGROUND_SECONDARY = "#202020"
BACKGROUND_TERTIARY = "#353535"
FOREGROUND_PRIMARY = "#FFFFFF"
FOREGROUND_SECONDARY = "#CCCCCC"
